auth.go
imqsauth/http.go
resttest.rb

See authaus commit message for justification of why we need this.

Add /rename_user API

---

imqsauth/http.go
imqsauth/yellowfin.go

Please review. There are changes in yfws and router as well.

include content category filter in YF logon

---

imqsauth/perms.go

added energy site action permissions

---

imqsauth/yellowfin.go

implement yf global filters

---

imqsauth/perms.go

File generated by InfrastructureBuild/auth/permissions/permissions.json

Energy: Info/PAC edit permissions

---

imqsauth/perms.go

TMM-1371:Employee Leave records (permissions)

---

auth.go
imqsauth/audit.go
imqsauth/config.go
imqsauth/http.go

TI-2093 - Auth log user attemps

---

resttest.rb

/users endpoint was changed thus,test needed to change to support said changes.

Fixed up resttest.eb for old API endpoint to match up with current one

---

auth.go
imqsauth/http.go

 TI-2402 - User list Filter

---

imqsauth/audit.go
imqsauth/http.go
imqsauth/net_tools.go

TI-2400 - Audit Trail Logging 

---

imqsauth/http.go
imqsauth/net_tools.go

Add extra audit actions

---

imqsauth/audit.go
imqsauth/http.go
imqsauth/net_tools.go

Fix for TI-2400 - Audit Log - Remove action type field

---

imqsauth/http.go

Fix:  TI-2701 - Audit trail fixes

---

imqsauth/yellowfin.go

Escape YF global filter values before logging in

---

imqsauth/config.go
imqsauth/http.go

ITOOLS-478 Move content of hostname file into environment variable

---

imqsauth/http.go
imqsauth/net_tools.go

Changes:
1) Refactor the client ip address capturing code to favour the server's hostname. We have not been able to log users ip addresses correctly, code returns 127.0.0.1 addresses which are not userful.
2) Refactor the auditUserLogAction method to take in extra parameters userId and username, for the cases where we do not have the logged in user's details. For example when resetting password and trying to log in.
3) Make reset password finish take in an extra config parameter for checking whether we can disable users from resusing old passwords.
Please review

TI-2869 - Refactor audit user logging

---

imqsauth/http.go

TI-2869 - Add ability to be able to send password expired message

---

imqsauth/http.go

TI-3017 - Add ability to audit user group changes

---

imqsauth/perms.go

TI-3142 - Add permission for work order creation tool

---

imqsauth/http.go
resttest.rb

Added `/userobjects?permission=1` API that only returns users with permission `1`

DC-140: Add API to get users that have specified permission

---

imqsauth/perms.go

TI-3346 - Add Road Signs module access permission

---

imqsauth/audit.go
imqsauth/http.go

TI-3417 - Add ability to log failed logins

---

auth.go
imqsauth/http.go

Add request to unlock user from front end

TI-3416 - Add unlock user pull and send IP to login

---

imqsauth/http.go
imqsauth/net_tools.go

Add client ip and email to audit log

TI-3417 - Report on Failed Logins in Audit Log

---

auth/perms.go
permissions/permissions.json

New permissions "IL – Documents Create" and "IL – Documents Delete" were added.

ALT-128: Incident Logger - Documents Permissions

---

auth/perms.go
permissions/permissions.json

The Archive permission for paydays had Edit instead of Archive.

Corrected the archive permission for paydays

---

auth/http.go
docs/API.md
docs/changelog.md

Add group id to /groups endpoint.

Add group id to /groups endpoint (ASG-3348)

---

auth/http.go
auth/tools.go
auth/tools_test.go

Changes were made to improve the audit log when making changes to roles of an user. A special case was also added to cater for disabling and enabling an user. 
Refs: NEXUS-4023

Improved audit log logging. 

---

auth/http.go

Ensure group changes works on user with no permit. In cases where a user has been newly created there is no permit yet. To cater for this a special check against the ErrIdentityPermitNotFound error has been added. That will then ignore this error since that means there is not permit that could be found. 
refs: NEXUS-4289

Ensure group changes works on user with no permit

---

auth/http.go
go.mod
go.sum

Draft pull request for when authaus PR is approved.

Use new getUserStatsAll function in authaus to combat perf issues
